### ISSUE TITLE
Create Docs for Library

### ISSUE THREAD

**Issue by uzaxirr** [integrateme-co/Notion-Blogger#11]
Prefer to use [docusaurus](https://docusaurus.io/)

**Comment by Souvikns** [comment]
I am thinking to creatre the docs in README.md itself becuase this library has just one function having a website for that would be overkill.

**Comment by uzaxirr** [comment]
> I am thinking to creatre the docs in README.md itself becuase this library has just one function having a website for that would be overkill.

If that's the case. Readme is fine
